name: hello_caen
description: Hello Caen App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # images
  flutter_svg: ^0.19.2+1
  image_picker: ^0.6.7+21

  # local
  shared_preferences: ^0.5.12+4
  flutter_local_notifications: ^3.0.3

  # location
  location: ^3.2.1
  # carp_background_location: ^1.0.2+1

  # dev
  provider: ^4.3.2+3
  intl: ^0.16.1
  timeago: ^2.0.29

  # firebase
  # firebase_database: ^4.4.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_messaging: "^8.0.0-dev.14"
  firebase_auth: "^0.20.0+1"

  # social auth
  google_sign_in: ^4.5.9
  flutter_facebook_auth: ^2.0.0+1

  # other
  flutter_rating_bar: ^3.2.0+1
  flutter_map: any
  uuid: ^2.2.2
  path_provider: ^1.6.27
  qr_flutter: ^3.2.0
  barcode_scan_fix: ^1.0.2
  pull_to_refresh: ^1.6.4
  charts_flutter: ^0.9.0
  diacritic: ^0.1.1
  flutter_map_marker_popup: ^0.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1 # ios icons

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
